// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB67y1lwB6xwRIKojhBYvM6eTZU9dhgCSU',
    appId: '1:477842904998:web:9368011deb76d1c0f32167',
    messagingSenderId: '477842904998',
    projectId: 'behboolun-meenjoke',
    authDomain: 'behboolun-meenjoke.firebaseapp.com',
    storageBucket: 'behboolun-meenjoke.firebasestorage.app',
    measurementId: 'G-KR06Y52G81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsSL1FbeMKhpG9JxoCPmbGO7MSUlZNwd4',
    appId: '1:477842904998:android:734d90bde670f3dcf32167',
    messagingSenderId: '477842904998',
    projectId: 'behboolun-meenjoke',
    storageBucket: 'behboolun-meenjoke.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6v0P9ijtK993wzqp9cSXpRJvic-4VzNg',
    appId: '1:477842904998:ios:a1cf0eb03650b929f32167',
    messagingSenderId: '477842904998',
    projectId: 'behboolun-meenjoke',
    storageBucket: 'behboolun-meenjoke.firebasestorage.app',
    iosClientId: '477842904998-a2uek8te15vosuclfqk31jshj9hceaca.apps.googleusercontent.com',
    iosBundleId: 'com.example.behboolunMeenjoke',
  );
}
